### ISSUE TITLE
Advanced Analysis button brings up TwoRavens with no data pebbles

### ISSUE THREAD

**Issue by pdurbin** [kevinworthington/dataverse#2]
Hi! I just clicked https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP/GUBPAJ via https://groups.google.com/d/msg/dataverse-community/Zpib-uCIG1g/mAx9BW8VBgAJ and noticed there's an "Advanced Analysis" button. I clicked it and it brings up TwoRavens but there are no "data pebbles" and I'm wondering if this is a known issue. Here are some screenshots:

![advanced1](https://cloud.githubusercontent.com/assets/21006/20107236/bd88b1f2-a5a5-11e6-921f-bf3235b448ce.png)
![advanced2](https://cloud.githubusercontent.com/assets/21006/20107237/bd91a2bc-a5a5-11e6-9c09-3c47d3698cf9.png)

**Comment by kevinworthington** [comment]
Hi Philip,
Thanks for flagging this in Git. The issue is as a result of TwoRavens not being properly installed on our server. We are working towards resolving this.

Kevin

**Comment by pdurbin** [comment]
@kevinworthington oh, so it's a known issue! Ok. I'll go ahead and close this then. You probably know this already but the docs on setting up TwoRavens are at http://guides.dataverse.org/en/4.5.1/installation/r-rapache-tworavens.html and if you have any feedback on them, you are welcome to open an issue at https://github.com/IQSS/dataverse since we keep the source of the docs in that repo. Great presentation the other day!

**Comment by kevinworthington** [comment]
Yes, this issue is being tracking in our intranet instillation of JIRA. 
It's nice of you to include the documentation for installing TwoRavens. Our systems administrator is tasked with fixing this so he'll likely have some feedback to contribute while using the documentation.
